name: Mario Vega Barbas
favicon: null
layout_spectrum: 0.25982
typography_spectrum: 0.24911
title: My Research World
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#060b0c'
    - '#707471'
    - '#3a4257'
    - '#a0a09f'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
