name: Mario Vega Barbas
favicon: null
layout_spectrum: 0.7640162182506174
typography_spectrum: 0.8851015830878168
title: My Research World
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#060b0c'
    - '#707471'
    - '#3a4257'
    - '#a0a09f'
  brandStrength: 0.6694138175807893
  lightness: 0
  saturation: 0.6589931340422481
  rhythmicContrast: 1
purpose: []
